services:
  aggregator:
    build: ./aggregation_service
    container_name: resource_aggregator
    restart: always
    volumes:
      - ./aggregation_service:/usr/src/app
    environment:
      - MONGO_URI=${MONGODB_URI}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
