services:
  mongodb:
    image: mongo:7.0
    container_name: learning_resources_db
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017

  aggregator:
    build: ./aggregation_service
    container_name: resource_aggregator
    restart: always
    volumes:
      - ./aggregation_service:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
    depends_on:
      - mongodb
